export const projectContent = [
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_1.jpg",
      title: "Illustrator Graphics",
      category: "Designing",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_2.jpg",
      title: "Figma Design",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_3.jpg",
      title: "Book Cover Mockup Design",
      category: "Branding",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_4.jpg",
      title: "Figma Design",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_5.jpg",
      title: "Illustrator Graphics",
      category: "Designing",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_6.jpg",
      title: "Book Cover Mockup Design",
      category: "Designing",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_7.jpg",
      title: "Creative Poster Design",
      category: "Branding",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_8.jpg",
      title: "Mobile App UI",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_9.jpg",
      title: "Modern Logo Design",
      category: "Designing",
    },,
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_8.jpg",
      title: "Mobile App UI",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_9.jpg",
      title: "Modern Logo Design",
      category: "Designing",
    },,
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_8.jpg",
      title: "Mobile App UI",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_9.jpg",
      title: "Modern Logo Design",
      category: "Designing",
    },,
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_8.jpg",
      title: "Mobile App UI",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_9.jpg",
      title: "Modern Logo Design",
      category: "Designing",
    },,
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_8.jpg",
      title: "Mobile App UI",
      category: "Application",
    },
    {
      addclass: "col-xl-4 col-lg-6 col-md-6",
      img: "/assets/images/portfolio/portfolio3_9.jpg",
      title: "Modern Logo Design",
      category: "Designing",
    },
  ];
